### PR TITLE
Decode XML entities

### PR DESCRIPTION
**Pull request by patrys**
Facebook feeds replace all diacritics outside of Latin 1 range with numerical entities. This pull request tries to fix it by implementing a workaround that replaces all entities with their corresponding characters.

I am however not sure hubot-rss-reader is the correct level to fix this. It feels like feedparser should be taking care of these (to make sure entries are not double-decoded in the rare case where they actually quote HTML/XML).

### CODE REVIEW

**Comment by shokai** [comment]
thank you, I'll check.

**Comment by patrys** [comment]
Example feed to show the problem: https://www.facebook.com/feeds/page.php?format=rss20&id=717064045041948

**Comment by shokai** [comment]
I have changed timing of decoding entities. do immediately after fetch feed.

**Comment by patrys** [comment]
Won't this result in entities like `&gt;` and `&lt;` breaking the resulting XML before it gets parsed?

**Comment by shokai** [comment]
It is ok, I mean

- 1. get XML
- 2. parse XML
- 3. decode description, summary, title in feeds

then send to chat.

**Pull request merged**
