### PR TITLE
fix room name when using hipchat adapter

### PR DESCRIPTION
**Pull request by motchang**
can't send to message when hipchat adapter

### CODE REVIEW

**Comment by shokai** [comment]
thanks!

**Comment by motchang** [comment]
🙏

**Comment by shokai** [comment]
maybe 
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L104
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L107
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L109
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L114
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L131
- https://github.com/shokai/hubot-rss-reader/blob/master/scripts/hubot-rss-reader.coffee#L149

should be fixed

**Comment by shokai** [comment]
I will try

**Comment by shokai** [comment]
@8a49e94 is ok on slack.

**Comment by shokai** [comment]
image

**Comment by motchang** [comment]
super cool!

**Comment by shokai** [comment]
I have [shipped](https://www.npmjs.com/package/hubot-rss-reader) v0.6.6

**Comment by shokai** [comment]
:beers:

**Comment by motchang** [comment]
its works clearly on heroku.
thank you very 🍣！

**Pull request merged**
